# Generated by Django 3.2 on 2022-01-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
