# Generated by Django 3.2 on 2022-03-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_release_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasepackage',
            name='source',
        ),
        migrations.AddField(
            model_name='releasepackage',
            name='is_source',
            field=models.BooleanField(default=True, help_text='True if the package is for source package'),
        ),
        migrations.AlterField(
            model_name='releasepackage',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='products.release'),
        ),
    ]
