# Generated by Django 3.2 on 2022-07-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_componenttreenode_producttreenode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerpackage',
            name='container',
        ),
        migrations.RemoveField(
            model_name='releasecontainer',
            name='container',
        ),
        migrations.RemoveField(
            model_name='releasecontainer',
            name='release',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='ContainerPackage',
        ),
        migrations.DeleteModel(
            name='ReleaseContainer',
        ),
    ]
