# Generated by Django 3.2 on 2022-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220714_0333'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producttreenode',
            constraint=models.UniqueConstraint(fields=('parent', 'object_id'), name='unique_parent_content_object'),
        ),
    ]
