# Generated by Django 3.2.16 on 2022-12-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_releasepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenttreenode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producttreenode',
            name='name',
        ),
        migrations.AddConstraint(
            model_name='componenttreenode',
            constraint=models.UniqueConstraint(fields=('parent', 'object_id'), name='unique_parent_content_object_ct'),
        ),
        migrations.AddConstraint(
            model_name='componenttreenode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('object_id',), name='unique_content_object_with_null_parent_ct'),
        ),
        migrations.AddConstraint(
            model_name='producttreenode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None)), fields=('object_id',), name='unique_content_object_with_null_parent'),
        ),
    ]
