stages:
  # Build ci-image if dockerfile changed
  - build-ci-image

  # Run static analysis tools
  # build PELC2 image
  - static-analysis-build

  # Run unit and functional tests that do not require fully deployed PELC
  # Run integration tests
  # Deploy master branch to pelc-dev
  - tests-it-promote

  - deploy-to-dev


variables:
  PELC_DATABASE_USER: postgres
  PELC_DATABASE_PASSWORD: test
  POSTGRESQL_ADMIN_PASSWORD: $DATABASE_PASSWORD
  OCP_ADDRESS: https://api.ocp-c1.prod.psi.redhat.com:6443
  CI_REGISTRY_IMAGE: quay.io/pelc/pelc2-ci
  PELC_IMAGE: quay.io/pelc/pelc2
  PELC_CI_USER: pelc+pelc_ci_cd
  PELC_CI_PASSWORD: $pelc_ci_cd_password

.ci-image: &ci-image
  image:
    name: $CI_REGISTRY_IMAGE:latest
  # the tags come from the labels of shared runner in 'gitlab.cee.redhat.com/pelc/pelc2/-/settings/ci_cd'
  tags:
    - pelc-docker-runner

.postgresql: &postgresql
  services:
    - 'quay.io/pelc/postgresql-12'


# ======== build-docker-ci  ========
# Image build will always be triggered, and will read cache from latest tag image
build-ci-image:
  tags:
    - pelc-shell-runner
  stage: build-ci-image
  script:
    - docker login -u="$PELC_CI_USER" -p=$PELC_CI_PASSWORD quay.io
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-caching-example
    # build and get local image sha id
    - LOCAL_IMAGE_SHA=`docker build  -q -f docker-ci/Dockerfile .`;
    - REMOTE_IMAGE_SHA=`skopeo inspect --format {{.Digest}} docker://$CI_REGISTRY_IMAGE:latest`
    # If remote latest tag is not equal to current then
    # push current image to latest
    - >
        if [ $LOCAL_IMAGE_SHA != $REMOTE_IMAGE_SHA ]; then
          echo "Existing same image,nothing to do";
        else
          echo "replace latest image"
          docker tag $CI_REGISTRY_IMAGE@$LOCAL_IMAGE_SHA $CI_REGISTRY_IMAGE:latest;
          docker push $CI_REGISTRY_IMAGE:latest;
        fi



# ======== static-analysis-build========
flake8:
  <<: *ci-image
  stage: static-analysis-build
  script:
    - if [ $CI_COMMIT_TAG = 'main' ];then
        echo "main branch, skip";
        exit 0;
      fi
    - tox -e flake8 --current-env


pylint:
  <<: *ci-image
  stage: static-analysis-build
  script:
    - if [ $CI_COMMIT_TAG = 'main' ];then
        echo "main branch, skip";
        exit 0;
      fi
    - tox -e pylint --current-env

# ======== tests-it-promote ========
unit-tests:
  <<: *ci-image
  <<: *postgresql
  stage: tests-it-promote
  script:
    - if [ $CI_COMMIT_TAG = 'main' ];then
        echo "main branch, skip";
        exit 0;
      fi
    - tox -e unit --current-env


# ======== deploy-to-dev ========

deploy-dev-instance:
  tags:
    - pelc-shell-runner
  only:
    refs:
      - main
  stage: deploy-to-dev
  script:
    - docker build --cache-from $PELC_IMAGE:dev
      --build-arg quay_expiration='90d'
      -t $PELC_IMAGE:dev
      -f docker-pelc/Dockerfile . ;
    - docker login -u="$PELC_CI_USER" -p=$PELC_CI_PASSWORD quay.io
    - docker push $PELC_IMAGE:dev
    # FIXME placeholder for future
    - echo 'trigger ansible tower job'
