stages:
  # Build ci-image if dockerfile changed
  - build-ci-image

  # Run static analysis tools
  # build PELC2 image
  - static-analysis-build

  # Run unit and functional tests that do not require fully deployed PELC
  # Run integration tests
  # Deploy master branch to pelc-dev
  - tests-it-promote

  - build-dev-image

  - deploy-to-dev

variables:
  TOWER_HOST: https://tower.engineering.redhat.com
  PELC_DATABASE_USER: postgres
  PELC_DATABASE_PASSWORD: test
  POSTGRESQL_ADMIN_PASSWORD: $DATABASE_PASSWORD
  OCP_ADDRESS: https://api.ocp-c1.prod.psi.redhat.com:6443
  CI_REGISTRY_IMAGE: quay.io/pelc/pelc2-ci
  PELC_IMAGE: quay.io/pelc/pelc2
  PELC_CI_USER: pelc+pelc_ci_cd
  PELC_CI_PASSWORD: $pelc_ci_cd_password

  # For pgsql start param
  POSTGRESQL_DATABASE: pelc2
  POSTGRESQL_USER: 'pelc2'
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRESQL_ADMIN_PASSWORD: 'test'
  POSTGRESQL_PASSWORD: 'test'

.ci-image: &ci-image
  image:
    name: $CI_REGISTRY_IMAGE:latest
  # the tags come from the labels of shared runner in 'gitlab.cee.redhat.com/pelc/pelc2/-/settings/ci_cd'
  tags:
    - pelc-docker-runner

.postgresql: &postgresql
  services:
    - 'quay.io/pelc/postgresql-12'

# ======== build-docker-ci  ========
# Image build will always be triggered, and will read cache from latest tag image
build-ci-image:
  tags:
    - pelc-shell-runner
  stage: build-ci-image
  script:
    - docker login -u="$PELC_CI_USER" -p=$PELC_CI_PASSWORD quay.io
    - cp containers/docker-ci/.dockerignore .
    # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-caching-example
    # build and get local image sha id
    - LOCAL_IMAGE_SHA=`docker build  -q -f containers/docker-ci/Dockerfile .`;
    - REMOTE_IMAGE_SHA=`skopeo inspect --format {{.Digest}} docker://$CI_REGISTRY_IMAGE:latest 2> /dev/null`
    # If remote latest tag is not equal to current then
    # push current image to latest
    - >
        if [ $LOCAL_IMAGE_SHA = $REMOTE_IMAGE_SHA ]; then
          echo "Existing same image, nothing to do";
        else
          echo "Replace latest image"
          docker tag $LOCAL_IMAGE_SHA $CI_REGISTRY_IMAGE:latest;
          docker push $CI_REGISTRY_IMAGE:latest;
        fi
    - rm -f .dockerignore

# ======== static-analysis-build========
flake8:
  <<: *ci-image
  stage: static-analysis-build
  script:
    - if [ $CI_COMMIT_REF_NAME = 'main' ];then
        echo "main branch, skip";
        exit 0;
      fi
    - tox -e flake8 --current-env

pylint:
  <<: *ci-image
  stage: static-analysis-build
  script:
    - if [ $CI_COMMIT_REF_NAME = 'main' ];then
        echo "main branch, skip";
        exit 0;
      fi
    - tox -e pylint --current-env

# ======== tests-it-promote ========
unit-tests:
  <<: *ci-image
  <<: *postgresql
  stage: tests-it-promote
  script:
    - if [ $CI_COMMIT_REF_NAME = 'main' ];then
        echo "main branch, skip";
        exit 0;
      fi
    - tox -e unit --current-env

api-tests:
  <<: *ci-image
  services:
    - name: 'quay.io/pelc/postgresql-12'
      alias: postgres
    - name: 'quay.io/pelc/redis'
      alias: redis
  stage: tests-it-promote
  script:
    - tox -e api --current-env

# ======== build-dev-image ========
build-dev-image:
 tags:
   - pelc-shell-runner
 only:
   refs:
     - main
 stage: build-dev-image
 script:
   - docker build -t $PELC_IMAGE:dev -f containers/docker-pelc/Dockerfile .;
   - docker login -u="$PELC_CI_USER" -p=$PELC_CI_PASSWORD quay.io
   - docker push $PELC_IMAGE:dev

deploy-to-dev:
  image:
    # Copy from perrit/ansible-tower-cli-container
    name: quay.io/pelc/ansible-tower-cli
  tags:
    - pelc-docker-runner
  only:
   refs:
     - main
  stage: deploy-to-dev
  script:
   - tower-cli config verify_ssl false
   - >
      tower-cli job launch -J "PELC2 deploy dev" --monitor --no-input --insecure
      -e "pelc_image_tag: dev"
      -h "$TOWER_HOST" -t "$TOWER_TOKEN"
