stages:
  # Build ci-image if dockerfile changed
  - build-ci-image

  # Run static analysis tools
  # build PELC2 image
  - static-analysis-build

  # Run unit and functional tests that do not require fully deployed PELC
  # Run integration tests
  # Deploy master branch to pelc-dev
  - tests-it-promote

  # Release new ci-image when merged
  - release-ci-image

variables:
  PELC_DATABASE_USER: postgres
  PELC_DATABASE_PASSWORD: test
  POSTGRESQL_ADMIN_PASSWORD: $DATABASE_PASSWORD
  OCP_ADDRESS: https://api.ocp-c1.prod.psi.redhat.com:6443

# images are built from openshift
# https://console-openshift-console.apps.ocp-c1.prod.psi.redhat.com/k8s/ns/pelc-ci-cd/buildconfigs/pelc2-gitlab-ci
.ci-image-commit: &ci-image-commit
  image:
    name: quay.io/pelc/pelc2-ci:$CI_COMMIT_SHA
  # the tags come from the labels of shared runner in 'gitlab.cee.redhat.com/pelc/pelc2/-/settings/ci_cd'
  tags:
    - docker
    - shared

.ci-image-latest: &ci-image-latest
  image:
    name: quay.io/pelc/pelc2-ci:latest
  # the tags come from the labels of shared runner in 'gitlab.cee.redhat.com/pelc/pelc2/-/settings/ci_cd'
  tags:
    - docker
    - shared

.postgresql: &postgresql
  services:
    - 'quay.io/pelc/postgresql-12'

.only-ci-image-latest: &only-ci-image-latest
  only:
    refs:
      - merge_requests
  except:
    changes:
      - "*.md"
      - ci-image/Dockerfile
      - requirements/base.txt
      - requirements/devel.txt

.only-ci-image-commit: &only-ci-image-commit
  only:
    changes:
      - ci-image/Dockerfile
      - requirements/base.txt
      - requirements/devel.txt
    refs:
      - merge_requests

## Currently, public runner no cache server
#.pip-cache: &pip-cache
#  cache:
#    # all branches and jobs will use the same cache
#    key: shared-key
#    paths:
#      - .cache/pip

# ======== build-ci-image  ========
build-ci-image:
  <<: *ci-image-latest
  <<: *only-ci-image-commit
  variables:
    PELC_PROJECT: "pelc2-dev"
  stage: build-ci-image
  artifacts:
    name: image-digest
    paths:
    - image-digest.txt
    expire_in: 30 days
  before_script:
    - oc login "$OCP_ADDRESS" --token "$PELC_CI_TOKEN"
    - oc project $PELC_PROJECT
  after_script:
    - oc logout
  script:
    - oc start-build pelc2-ci
      -o name
      --commit "$CI_COMMIT_SHA"
      --follow --wait
      | tee output
    - oc get "$(head -n1 output)" -o jsonpath='{.status.output.to.imageDigest}' > image-digest.txt
    - if [ ! -s image-digest.txt ]; then
          echo "The image build not success, please rerun this step!!!"
          exit 1 ;
      fi
    #To avoid untagged image will be automatically deleted
    - skopeo copy
      --src-creds=$QUAY_USERNAME:$QUAY_TOKEN
      --dest-creds=$QUAY_USERNAME:$QUAY_TOKEN
      docker://quay.io/pelc/pelc2-ci@$(cat image-digest.txt)
      docker://quay.io/pelc/pelc2-ci:$CI_COMMIT_SHA

# ======== test-unit-style ========
flake8-commit:
  <<: *ci-image-commit
  <<: *only-ci-image-commit
  stage: static-analysis-build
  script:
    - tox -e flake8 --current-env

flake8-latest:
  <<: *ci-image-latest
  <<: *only-ci-image-latest
  stage: static-analysis-build
  script:
    - tox -e flake8 --current-env

pylint-commit:
  <<: *ci-image-commit
  <<: *only-ci-image-commit
  stage: static-analysis-build
  script:
    - tox -e pylint --current-env

pylint-latest:
  <<: *ci-image-latest
  <<: *only-ci-image-latest
  stage: static-analysis-build
  script:
    - tox -e pylint --current-env

unit-tests-commit:
  <<: *ci-image-commit
  <<: *postgresql
  <<: *only-ci-image-commit
  stage: tests-it-promote
# # Currently, no shared runner, comment these code
#  artifacts:
#    name: unit-tests-coverage
#    paths:
#    - .coverage.*
#    expire_in: 30 days
  script:
    - tox -e unit --current-env


unit-tests-latest:
  <<: *ci-image-latest
  <<: *postgresql
  <<: *only-ci-image-latest
  stage: tests-it-promote
# # Currently, no shared runner, comment these code
#  artifacts:
#    name: unit-tests-coverage
#    paths:
#    - .coverage.*
#    expire_in: 30 days
  script:
    - tox -e unit --current-env

# ======== release-ci-image  ========
release-ci-image:
  <<: *ci-image-latest
  variables:
    PELC_PROJECT: "pelc2-dev"
  only:
    changes:
      - ci-image/Dockerfile
      - requirements/base.txt
      - requirements/devel.txt
    refs:
      - main
  stage: release-ci-image
  script:
    - skopeo copy
      --src-creds=$QUAY_USERNAME:$QUAY_TOKEN
      --dest-creds=$QUAY_USERNAME:$QUAY_TOKEN
      docker://quay.io/pelc/pelc2-ci:$CI_COMMIT_SHA
      docker://quay.io/pelc/pelc2-ci:latest
