# Generated by Django 3.2 on 2022-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetection',
            name='detector',
            field=models.CharField(help_text='License detector with version detail', max_length=32),
        ),
        migrations.AlterField(
            model_name='licensedetection',
            name='license_key',
            field=models.CharField(max_length=128, verbose_name='license identifier'),
        ),
        migrations.AlterUniqueTogether(
            name='licensedetection',
            unique_together=set(),
        ),
    ]
