# Generated by Django 3.2 on 2022-02-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220224_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='copyrightdetection',
            unique_together=set(),
        ),
    ]
