# Generated by Django 3.2 on 2022-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_source_checksum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='path',
            name='unique_source_file_path',
        ),
        migrations.AddConstraint(
            model_name='path',
            constraint=models.UniqueConstraint(fields=('source', 'path'), name='unique_source_path'),
        ),
    ]
