# Generated by Django 3.2 on 2022-03-07 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_path_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='source',
            field=models.ForeignKey(help_text='Reference to source package', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.source'),
        ),
    ]
