# Generated by Django 3.2 on 2022-07-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_source_scan_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='Corgi component uuid', unique=True)),
                ('type', models.CharField(help_text='Corgi component type', max_length=50)),
                ('name', models.TextField()),
                ('version', models.CharField(max_length=1024)),
                ('release', models.CharField(default='', max_length=1024)),
                ('arch', models.CharField(default='', max_length=1024)),
                ('purl', models.CharField(blank=True, default='', help_text='Corgi component purl', max_length=1024)),
                ('summary_license', models.TextField(blank=True, help_text='Declared summary license expression')),
                ('is_source', models.BooleanField(default=False, help_text='True if this component corresponds to the entire source, rather than an actual binary package')),
                ('source', models.ForeignKey(blank=True, help_text='Reference to component source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('name', 'version', 'release', 'arch', 'type'), name='unique_components'),
        ),
    ]
