# Generated by Django 3.2 on 2022-08-02 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20220704_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='synced',
            field=models.BooleanField(default=False, help_text='Indicate whether the component is synced with component from component registry. Synced component should have identical uuid.'),
        ),
        migrations.AlterField(
            model_name='component',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Component uuid', unique=True),
        ),
    ]
