# Generated by Django 3.2.14 on 2022-08-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20220802_0346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
