# Generated by Django 3.2.14 on 2022-08-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_delete_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='summary_license',
            field=models.TextField(blank=True, default='', help_text='Declared summary license expression'),
        ),
    ]
