# Generated by Django 3.2.16 on 2023-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_componentsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='synced',
        ),
        migrations.AddField(
            model_name='component',
            name='from_corgi',
            field=models.BooleanField(default=False, help_text='True if created from component registry'),
        ),
        migrations.AddField(
            model_name='component',
            name='sync_failure_reason',
            field=models.CharField(blank=True, choices=[('request_timeout', 'Request timeout'), ('scan_exception', 'Scan exception'), ('missing_download_url', 'Missing download url'), ('unknown_failure', 'Unknown failure')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('unsynced', 'Unsynced'), ('sync_failed', 'Sync Failed')], default='unsynced', max_length=50),
        ),
    ]
