# Generated by Django 3.2.18 on 2023-05-10 06:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_componentsubscription_missing_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsubscription',
            name='source_purls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, default=list, null=True, size=None),
        ),
    ]
