# Generated by Django 3.2.19 on 2023-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_componentsubscription_source_purls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentsubscription',
            name='missing_components',
        ),
        migrations.CreateModel(
            name='MissingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purl', models.CharField(help_text='Corgi component purl', max_length=1024, unique=True)),
                ('subscriptions', models.ManyToManyField(related_name='missing_components', to='packages.ComponentSubscription')),
            ],
        ),
    ]
