# Generated by Django 3.2.19 on 2023-06-21 16:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedHatProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('sub', models.UUIDField(default=uuid.uuid4)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, default=list, null=True, size=None)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
