# Generated by Django 3.2.19 on 2023-07-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230621_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redhatprofile',
            name='roles',
        ),
    ]
