# Generated by Django 3.2 on 2021-11-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swhid', models.CharField(help_text='SoftWare Heritage persistent IDentifier', max_length=50, verbose_name='SWH ID')),
            ],
        ),
    ]
