# Generated by Django 3.2 on 2021-11-30 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_file_swhid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(help_text='Checksum for this package', max_length=50)),
                ('name', models.CharField(help_text='Name of this package', max_length=128)),
                ('url', models.TextField(blank=True, help_text='Upstream project URL', null=True, validators=[django.core.validators.URLValidator(message='Please enter a valid URL.')], verbose_name='URL')),
                ('state', models.IntegerField(default=0, help_text='Used to track package analysis status')),
                ('archive_type', models.CharField(help_text='Type of archive', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(help_text='File path within source package')),
                ('file', models.ForeignKey(help_text='Reference to a file', on_delete=django.db.models.deletion.CASCADE, to='packages.file')),
                ('source', models.ForeignKey(help_text='Reference to source package', on_delete=django.db.models.deletion.CASCADE, to='packages.source')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr', models.CharField(help_text='Package nvr', max_length=512, verbose_name='NVR')),
                ('sum_license', models.TextField(blank=True, help_text='File path within source package', null=True)),
                ('is_source', models.BooleanField(default=False, help_text='True if this package corresponds to the entire source, rather than an actual binary package')),
                ('source', models.ForeignKey(help_text='Reference to source package', on_delete=django.db.models.deletion.CASCADE, to='packages.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='path',
            constraint=models.UniqueConstraint(fields=('source', 'file', 'path'), name='unique_source_file_path'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('nvr', 'source'), name='unique_nvr_source'),
        ),
    ]
