# Generated by Django 3.2 on 2021-12-15 02:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='license identifier')),
                ('score', models.FloatField(blank=True, help_text='License match score (0 - 100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rule', models.TextField(blank=True, help_text='How the license is detected', null=True)),
                ('start_line', models.IntegerField(blank=True, help_text='Beginning of license match', null=True)),
                ('end_line', models.IntegerField(blank=True, help_text='End of license match', null=True)),
                ('false_positive', models.BooleanField(default=False, help_text='True if this detection is a false positive')),
                ('detector', models.CharField(help_text='License detecor with version detail', max_length=32)),
                ('file', models.ForeignKey(help_text='Reference to a file', on_delete=django.db.models.deletion.CASCADE, to='packages.file')),
            ],
            options={
                'unique_together': {('file', 'detector')},
            },
        ),
        migrations.CreateModel(
            name='CopyrightDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, help_text='Copyright statement', null=True)),
                ('false_positive', models.BooleanField(default=False, help_text='True if this detection is a false positive')),
                ('start_line', models.IntegerField(blank=True, help_text='Beginning of copyright match', null=True)),
                ('end_line', models.IntegerField(blank=True, help_text='End of copyright match', null=True)),
                ('detector', models.CharField(help_text='Copyright detector with version detail', max_length=32)),
                ('file', models.ForeignKey(help_text='Reference to a file', on_delete=django.db.models.deletion.CASCADE, to='packages.file')),
            ],
            options={
                'unique_together': {('file', 'detector')},
            },
        ),
    ]
