# Generated by Django 3.2.15 on 2022-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=155, unique=True)),
                ('status', models.CharField(max_length=50, verbose_name='state')),
                ('result', models.BinaryField(default=None, null=True)),
                ('date_done', models.DateTimeField(auto_now=True, null=True, verbose_name='date_done')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='traceback')),
            ],
            options={
                'db_table': 'celery_taskmeta',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task_id',
            field=models.TextField(default=''),
        ),
    ]
