# Generated by Django 3.2 on 2022-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filecopyrightscan',
            constraint=models.UniqueConstraint(fields=('file', 'detector'), name='unique_file_copyright_scan'),
        ),
        migrations.AddConstraint(
            model_name='filelicensescan',
            constraint=models.UniqueConstraint(fields=('file', 'detector'), name='unique_file_license_scan'),
        ),
    ]
