# Generated by Django 3.2.16 on 2023-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220316_0505'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='copyrightdetection',
            constraint=models.UniqueConstraint(fields=('statement', 'false_positive', 'start_line', 'end_line', 'file_scan'), name='unique_copyright_detection'),
        ),
        migrations.AddConstraint(
            model_name='licensedetection',
            constraint=models.UniqueConstraint(fields=('license_key', 'score', 'rule', 'start_line', 'end_line', 'false_positive', 'file_scan'), name='unique_license_detection'),
        ),
    ]
