# Generated by Django 3.2 on 2021-12-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_nvr', models.TextField()),
                ('source', models.SmallIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.container')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.release')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_nvr', models.TextField()),
                ('source', models.SmallIntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.container')),
            ],
        ),
        migrations.AddConstraint(
            model_name='releasepackage',
            constraint=models.UniqueConstraint(fields=('release', 'package_nvr'), name='unique_release_package_nvr'),
        ),
        migrations.AddConstraint(
            model_name='releasecontainer',
            constraint=models.UniqueConstraint(fields=('release', 'container'), name='unique_release_container'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_product_version'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('product', 'version')},
        ),
        migrations.AddConstraint(
            model_name='containerpackage',
            constraint=models.UniqueConstraint(fields=('container', 'package_nvr'), name='unique_container_package'),
        ),
    ]
